//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.CameraCaptureViewDesignData
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class CameraCaptureViewDesignData { }
#else

	public class CameraCaptureViewDesignData : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public CameraCaptureViewDesignData()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/AccessingWP7Devices;component/SampleData/CameraCaptureViewDesignData/CameraCaptureViewDesignData.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private System.Windows.Media.ImageSource _Source = null;

		public System.Windows.Media.ImageSource Source
		{
			get
			{
				return this._Source;
			}

			set
			{
				if (this._Source != value)
				{
					this._Source = value;
					this.OnPropertyChanged("Source");
				}
			}
		}

		private string _Position = string.Empty;

		public string Position
		{
			get
			{
				return this._Position;
			}

			set
			{
				if (this._Position != value)
				{
					this._Position = value;
					this.OnPropertyChanged("Position");
				}
			}
		}

		private string _Address = string.Empty;

		public string Address
		{
			get
			{
				return this._Address;
			}

			set
			{
				if (this._Address != value)
				{
					this._Address = value;
					this.OnPropertyChanged("Address");
				}
			}
		}

		private string _Note = string.Empty;

		public string Note
		{
			get
			{
				return this._Note;
			}

			set
			{
				if (this._Note != value)
				{
					this._Note = value;
					this.OnPropertyChanged("Note");
				}
			}
		}

		private string _DateTaken = string.Empty;

		public string DateTaken
		{
			get
			{
				return this._DateTaken;
			}

			set
			{
				if (this._DateTaken != value)
				{
					this._DateTaken = value;
					this.OnPropertyChanged("DateTaken");
				}
			}
		}
	}
#endif
}
