//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.NotificationBoxDesignData
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class NotificationBoxDesignData { }
#else

	public class NotificationBoxDesignData : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public NotificationBoxDesignData()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/AccessingWP7Devices;component/SampleData/NotificationBoxDesignData/NotificationBoxDesignData.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Buttons _Buttons = new Buttons();

		public Buttons Buttons
		{
			get
			{
				return this._Buttons;
			}
		}

		private bool _ShowAgain = false;

		public bool ShowAgain
		{
			get
			{
				return this._ShowAgain;
			}

			set
			{
				if (this._ShowAgain != value)
				{
					this._ShowAgain = value;
					this.OnPropertyChanged("ShowAgain");
				}
			}
		}

		private string _Title = string.Empty;

		public string Title
		{
			get
			{
				return this._Title;
			}

			set
			{
				if (this._Title != value)
				{
					this._Title = value;
					this.OnPropertyChanged("Title");
				}
			}
		}

		private string _Message = string.Empty;

		public string Message
		{
			get
			{
				return this._Message;
			}

			set
			{
				if (this._Message != value)
				{
					this._Message = value;
					this.OnPropertyChanged("Message");
				}
			}
		}
	}

	public class ButtonsItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Content = string.Empty;

		public string Content
		{
			get
			{
				return this._Content;
			}

			set
			{
				if (this._Content != value)
				{
					this._Content = value;
					this.OnPropertyChanged("Content");
				}
			}
		}
	}

	public class Buttons : System.Collections.ObjectModel.ObservableCollection<ButtonsItem>
	{ 
	}
#endif
}
