//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.MapViewDesignData
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class MapViewDesignData { }
#else

	public class MapViewDesignData : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public MapViewDesignData()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/AccessingWP7Devices;component/SampleData/MapViewDesignData/MapViewDesignData.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Pictures _Pictures = new Pictures();

		public Pictures Pictures
		{
			get
			{
				return this._Pictures;
			}
		}

		private bool _InPreviewMode = false;

		public bool InPreviewMode
		{
			get
			{
				return this._InPreviewMode;
			}

			set
			{
				if (this._InPreviewMode != value)
				{
					this._InPreviewMode = value;
					this.OnPropertyChanged("InPreviewMode");
				}
			}
		}

		private PreviewPicture _PreviewPicture = new PreviewPicture();

		public PreviewPicture PreviewPicture
		{
			get
			{
				return this._PreviewPicture;
			}

			set
			{
				if (this._PreviewPicture != value)
				{
					this._PreviewPicture = value;
					this.OnPropertyChanged("PreviewPicture");
				}
			}
		}
	}

	public class Pictures : System.Collections.ObjectModel.ObservableCollection<PicturesItem>
	{ 
	}

	public class PicturesItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private System.Windows.Media.ImageSource _Source = null;

		public System.Windows.Media.ImageSource Source
		{
			get
			{
				return this._Source;
			}

			set
			{
				if (this._Source != value)
				{
					this._Source = value;
					this.OnPropertyChanged("Source");
				}
			}
		}

		private string _Note = string.Empty;

		public string Note
		{
			get
			{
				return this._Note;
			}

			set
			{
				if (this._Note != value)
				{
					this._Note = value;
					this.OnPropertyChanged("Note");
				}
			}
		}

		private string _Position = string.Empty;

		public string Position
		{
			get
			{
				return this._Position;
			}

			set
			{
				if (this._Position != value)
				{
					this._Position = value;
					this.OnPropertyChanged("Position");
				}
			}
		}
	}

	public class PreviewPicture : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private System.Windows.Media.ImageSource _Source = null;

		public System.Windows.Media.ImageSource Source
		{
			get
			{
				return this._Source;
			}

			set
			{
				if (this._Source != value)
				{
					this._Source = value;
					this.OnPropertyChanged("Source");
				}
			}
		}
	}
#endif
}
